# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build-and-test:
    #docker:
    #  - image: cimg/openjdk:11.0
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Test
          command: mvn verify

workflows:
  workflow:
    jobs:
      - build-and-test
