name: Main Branch CI

on:
  push:
    branches:
      - 'main'

jobs:
  build-apis:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    #defaults:
    #  run:
    #    working-directory: ./geeksclub-api-springboot
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: ./mvnw clean verify

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Publish Docker Images
        run: |
          ./mvnw spring-boot:build-image -pl geeksclub-api-springboot
          docker push ${{ secrets.DOCKER_USER }}/geeksclub-api-springboot
